apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-front
  labels:
    app: angular-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-front
  template:
    metadata:
      labels:
        app: angular-front
    spec:
      containers:
        - name: angular-kube
          image: roberechev/angularfrontend:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 80